### ISSUE TITLE
Inequality between Electric Terrain and +1 ability boost

### ISSUE THREAD

**Issue by Dennis-Sun** [smogon/damage-calc#310]
These two calculations should provide the same results (because both electric terrain and +1 should have a 1.5 damage multiplier), but they do not:

> 252 SpA Tapu Koko Gigavolt Havoc (175 BP) vs. 212 HP / 20 SpD Kangaskhan-Mega in Electric Terrain: 178-211 (85.9 - 101.9%) -- 18.8% chance to OHKO
Possible damage amounts: (178, 181, 183, 186, 187, 189, 192, 193, 196, 198, 199, 202, 204, 207, 208, 211)

vs
> +1 252 SpA Tapu Koko Gigavolt Havoc (175 BP) vs. 212 HP / 20 SpD Kangaskhan-Mega: 177-208 (85.5 - 100.4%) -- 6.3% chance to OHKO
Possible damage amounts: (177, 178, 180, 183, 184, 187, 189, 190, 193, 195, 198, 199, 201, 204, 205, 208)

**Comment by AustinXII** [comment]
I suspect L#837 is the culprit. Terrain uses pokeRound, modifiers use math.floor. Are you sure terrain’s aren’t just handled later in the calculation than stat modifiers because the calculations are very close? Electric terrain definitely has the correct 1.5x modifier

**Comment by scheibo** [comment]
I'm trying to repro this but I must be missing some context? I'm getting a completely different calc:

> 252 SpA Tapu Koko Gigavolt Havoc (175 BP) vs. 212 HP / 20 SpD Kangaskhan-Mega in Electric Terrain: 337-397 (83.4 - 98.2%) -- guaranteed 2HKO
Possible damage amounts: (337, 340, 345, 349, 352, 357, 361, 364, 369, 373, 376, 381, 385, 388, 393, 397)

> +1 252 SpA Tapu Koko Gigavolt Havoc (175 BP) vs. 212 HP / 20 SpD Kangaskhan-Mega: 339-399 (83.9 - 98.7%) -- guaranteed 2HKO
Possible damage amounts: (339, 342, 346, 351, 354, 358, 363, 366, 370, 375, 378, 382, 387, 390, 394, 399)

I'm thinking this is possibly because the move modifier order was overhauled in https://github.com/smogon/damage-calc/commit/a056d403b2cb347c0bd9488cc8f0ec364f8f90c8?

Anyway, plugging it into the long form damage calculator which is the most accurate calc:

![Screen Shot 2020-04-18 at 13 08 26](https://user-images.githubusercontent.com/117249/79670142-c8e79b80-8175-11ea-8793-2a5a7dfba058.png)

The range of values for Electric terrain looks dead on (yay!). If we change from electric terrain to a +1 boost.

![Screen Shot 2020-04-18 at 13 10 19](https://user-images.githubusercontent.com/117249/79670180-fdf3ee00-8175-11ea-8a5b-8bea016cea94.png)

Once again, we are (admittedly, somewhat very surprisingly) dead on! 

@AustinXII for FYI/@DaWoblefet to check my work, but closing as WAI now after the OZY modifier change has been implemented

**Comment by DaWoblefet** [comment]
Verifying OZY updates fixed this.

252 SpA Tapu Koko Gigavolt Havoc (175 BP) vs. 212 HP / 20 SpD Kangaskhan-Mega in Electric Terrain: 177-208 (85.5 - 100.4%) -- 6.3% chance to OHKO
Possible damage amounts: (177, 178, 180, 183, 184, 187, 189, 190, 193, 195, 198, 199, 201, 204, 205, 208)

+1 252 SpA Tapu Koko Gigavolt Havoc (175 BP) vs. 212 HP / 20 SpD Kangaskhan-Mega: 177-208 (85.5 - 100.4%) -- 6.3% chance to OHKO
Possible damage amounts: (177, 178, 180, 183, 184, 187, 189, 190, 193, 195, 198, 199, 201, 204, 205, 208)

^Note the user was using level 50 numbers rather than level 100. They are definitely different multipliers (Terrains are base power, +1 is an attack modifier), but they happen to come out to be the same base damage.
