### ISSUE TITLE
Add new Isle of Armor species and move data

### ISSUE THREAD

**Issue by ajhyndman** [smogon/damage-calc#398]
I'm happy to help with this.

From skimming the README's it looks like this data should be pulled/copied from an upstream source somehow?  I didn't see steps to do so spelled out anywhere though.

Edit:

I just saw #397!  Looks it's already underway.  I look forward to the next npm release.  :)

**Comment by AustinXII** [comment]
@scheibo is going to be on a break for a few weeks and is the one who deals with that... sadly the npm release may come a bit after the calc lands

**Comment by scheibo** [comment]
Apparently I didn't turn of GH notifications yet. @ me when it's ready to be released and I can do it, though Marty should be able to as well

**Comment by ajhyndman** [comment]
@scheibo it looks like #397 landed.  🙂

**Comment by scheibo** [comment]
Yes, but the build is broken. I'll check back tomorrow

**Comment by AustinXII** [comment]
@scheibo the build is broken because of pkmn/data

**Comment by scheibo** [comment]
No, that is in fact not why the build is broken.

**Comment by AustinXII** [comment]
@scheibo ? the error is unexpected data lengths ? Unless I'm missing something here https://github.com/smogon/damage-calc/runs/791861848

**Comment by scheibo** [comment]
I'm really *really* peeved off right now that I'm spending my morning fixing your typos because you (and Kris?) assume the test is wrong and not your data entry. The only error so far I see with `@pkmn/dex` (which is what the calc's tests depend on, not `@pkmn/data`) is that it lists Kubfu's speed as 73 and not 72 due to when the package was cut (which can trividally worked around by simply either leaving it incorrect to pass the test with a `// FIXME`` comment given how inconsequential it is to the damage calc, or just hardcoded into the test to work around the out of date data dependency).

Please stop breaking the build, this test **LITERALLY EXISTS FOR THIS EXACT REASON**.

**Comment by AustinXII** [comment]
@scheibo if you are going to be gone for a while I'm not really going to care much about a test failing because of dependency I can not fix that has has incorrect info. I don't really want to push incorrect info to the calc in sake of having a test pass that literally only affects me (and maybe the one off rare contributor) while you are gone.

**Comment by scheibo** [comment]
Hmm... lets see. From this "dependency I can not fix (why? are you unable to make a PR against that repository???) that has has incorrect infoIs Kubfu's speed being off by 1 ("more or less important than:

- Venusaur Gmax being given Levitate instead of Overgrow, and Poison Fairy instead of Grass Poison
- Kubfu not being marked as NFE
- Intelegon-Gmax being given 'Torent'  instead of Torrent
- Magearna-Original not being present
- Rillaboom-Gmax being given Runaway instead of Overgrow
- Urshifu being given Toxitricity's information instead of its own

Which is what I've fixed so far, and theres more to come with moves.

This does not 'literally only effect you' - you're asking me to publish a package that is frozen in time and effects downstream developers. I am completely reasonable to not want to cut a release with obvious errors that our developers would then be forced to work around.

**Comment by scheibo** [comment]
I have released `@smogon/calc` v0.4.0. 

@AustinXII - please read over the commits I pushed to understand:

a) Why `data.test.ts` is valuable
b) How to work around the `@pkmn/dex` package potentially reflecting out of data information

`data.test.ts` can and should certainly be improved to be easier to understand (the most glaring part I noticed is that the expected and received information is in reverse), but it 100% is correct at identifying when smogon/calc's data has a discrepancy with a snapshot of Pokemon Showdown's data. If the test was for some reason catastrophically wrong  (hint, it isnt) you could have added a `.pending` to the test to not break the build (though your changes also included lint errors).

I have updated the random sets, pushed the DLC package and deployed the fixed data on calc.pokemonshowdown.com. I am now muting GitHub.

**Comment by KrisXV** [comment]
Don’t wrap me into this. I was just reviewing the data, the build wasn’t my focus.

**Comment by ajhyndman** [comment]
@scheibo Thank you for cleaning this up and releasing.

In the future, I don't mind being asked for review or contributions.  Having this package up to date and accurate lets me update https://eevaluator.ajhyndman.com, which I want to keep relevant for my users!
